import XCTest
import AppKit
@testable import Core
@testable import OpenClip

@MainActor
final class PasteboardCopyEngineTests: XCTestCase {
    private static let pasteboardName = NSPasteboard.Name("com.openclip.tests.copyengine")
    private var pasteboard: NSPasteboard!

    override func setUp() {
        super.setUp()
        pasteboard = NSPasteboard(name: Self.pasteboardName)
        pasteboard.clearContents()
    }

    override func tearDown() {
        pasteboard.clearContents()
        pasteboard = nil
        super.tearDown()
    }

    func testTriggerChangesContentReturnsNewStringRestoresOriginalWithTransientMarkers() async throws {
        pasteboard.clearContents()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.captureString(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Copied", forType: .string)
        }

        XCTAssertEqual(captured, "Copied")

        try await Task.sleep(nanoseconds: UInt64((Constants.pasteboardRestoreDelay + 0.1) * 1_000_000_000))

        XCTAssertEqual(pasteboard.string(forType: .string), "Original")

        let transient = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")) ?? Data()
        let autoGenerated = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")) ?? Data()
        XCTAssertEqual(transient, Data())
        XCTAssertEqual(autoGenerated, Data())
    }

    func testTriggerWritingBackSameTextReturnsText() async throws {
        pasteboard.clearContents()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.captureString(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Original", forType: .string)
        }

        // The changeCount advances, so the write is accepted even though the value matches the
        // archived original (a re-copy of the same text is a legitimate copy).
        XCTAssertEqual(captured, "Original")
    }

    func testTimeoutTriggerReturnsNilAndRestoresOriginal() async throws {
        pasteboard.clearContents()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.captureString(
            pasteboard: pasteboard,
            timeout: 0.05,
            restoreDelay: 0.05
        ) {
            // Trigger never copies: the changeCount never advances.
        }

        XCTAssertNil(captured)
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")
    }

    func testHasSelection() {
        XCTAssertFalse(PasteboardCopyEngine.hasSelection(nil))
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("   "))
        XCTAssertTrue(PasteboardCopyEngine.hasSelection("x"))
    }
}