import XCTest
import AppKit
@testable import Core
@testable import OpenClip

@MainActor
final class PasteboardCopyEngineTests: XCTestCase {
    private static let pasteboardName = NSPasteboard.Name("com.openclip.tests.copyengine")
    private var pasteboard: NSPasteboard!

    override func setUp() {
        super.setUp()
        pasteboard = NSPasteboard(name: Self.pasteboardName)
        pasteboard.clearContents()
    }

    override func tearDown() {
        pasteboard.clearContents()
        pasteboard = nil
        super.tearDown()
    }

    func testTriggerChangesContentReturnsNewStringRestoresOriginalWithTransientMarkers() async throws {
        pasteboard.clearContents()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.captureString(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Copied", forType: .string)
        }

        XCTAssertEqual(captured, "Copied")

        // The original is restored synchronously before captureString returns — no delayed cleanup
        // task that could race and leave the copied text behind.
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")

        let transient = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")) ?? Data()
        let autoGenerated = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")) ?? Data()
        XCTAssertEqual(transient, Data())
        XCTAssertEqual(autoGenerated, Data())
    }

    func testTriggerWritingBackSameTextReturnsText() async throws {
        pasteboard.clearContents()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.captureString(pasteboard: pasteboard) {
            pasteboard.clearContents()
            pasteboard.setString("Original", forType: .string)
        }

        // The changeCount advances, so the write is accepted even though the value matches the
        // archived original (a re-copy of the same text is a legitimate copy).
        XCTAssertEqual(captured, "Original")
    }

    func testTimeoutTriggerReturnsNilAndRestoresOriginal() async throws {
        pasteboard.clearContents()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.captureString(
            pasteboard: pasteboard,
            timeout: 0.05,
            restoreDelay: 0.05
        ) {
            // Trigger never copies: the changeCount never advances.
        }

        XCTAssertNil(captured)
        XCTAssertEqual(pasteboard.string(forType: .string), "Original")

        let transient = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.TransientType")) ?? Data()
        let autoGenerated = pasteboard.data(forType: NSPasteboard.PasteboardType(rawValue: "org.nspasteboard.AutoGeneratedType")) ?? Data()
        XCTAssertEqual(transient, Data())
        XCTAssertEqual(autoGenerated, Data())
    }

    func testTransientEmptyWriteThenTextIsCaptured() async {
        pasteboard.clearContents()
        pasteboard.setString("Original", forType: .string)

        let engine = PasteboardCopyEngine()
        let captured = await engine.captureString(
            pasteboard: pasteboard,
            timeout: 1.0,
            restoreDelay: 0.05
        ) {
            // Simulate the PopClip-style race: the changeCount advances with empty content first,
            // then the real selection lands a beat later.
            Task { @MainActor in
                pasteboard.clearContents()
                pasteboard.setString("", forType: .string)
                try? await Task.sleep(nanoseconds: 20_000_000)
                pasteboard.clearContents()
                pasteboard.setString("Real selection", forType: .string)
            }
        }

        XCTAssertEqual(captured, "Real selection")
    }

    func testHasSelection() {
        XCTAssertFalse(PasteboardCopyEngine.hasSelection(nil))
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("   "))
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("\u{00A0}\u{00A0}")) // Non-breaking spaces
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("\u{200B}\u{FEFF}")) // Zero-width spaces
        XCTAssertFalse(PasteboardCopyEngine.hasSelection("\u{0000}")) // Null byte
        XCTAssertTrue(PasteboardCopyEngine.hasSelection("x"))
        XCTAssertTrue(PasteboardCopyEngine.hasSelection("  hello  "))
    }
}